### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by pietrisko** [NKI-CCB/won-parafac#1]
Hi,

when I run the demo I get this error:

Error using norm
Input must be 2-D.

Error in wonparafac (line 84)
normX = norm(WeightW.*X)

**Comment by anoyaro84** [comment]
Can you check which norm function you are using now?
It should be from the tensor toolbox.

Hope this helps.

**Comment by anoyaro84** [comment]
Actually, I think the line causing the error is not necessary. I updated the script. (merely just removing one line).
