### ISSUE TITLE
Demo options.rate parameter

### ISSUE THREAD

**Issue by inuritdino** [NKI-CCB/won-parafac#2]
Hi,

thanks for the tool! I am trying to run the demo script and came across this option:
`options.rate = 1`

Is it a learning rate (`\nu` from the paper)? But I cannot find it in `wonparafac.m` and how it affects the learning in the code.

Another question I have is: I am trying to reproduce the decomposition from the paper and barely reaching the fit value of 0.5 (on tol=1e-7 and maxiters=500). Should I increase number of iterations further, because the fit value is very low? I am loading the whole data cube from `Demo.mat` as it was used in the paper I believe.

Maybe you could tell me what parameters did you use for the paper results.

Otherwise, I would like to thank you for the great job and a nice tool!

Thank you in advance for your answers!

**Comment by anoyaro84** [comment]
Thank you for your interest in our tool.

`options.rate` is indeed not used in won-parafac anymore.
(we used to have them in the previous version under development)
So it should not do anything to the outcome of the algorithm.

I will delete that part to make it not confusing.

In terms of the reconstruction error, the most impacting factors should be the number of factors and the level of orthogonality constraint.
The Demo result was created using the script on Github as is.
So I expect that you can reproduce the same outcome if you use the same setting.

I hope this answers the question.
